### ISSUE TITLE
Columns bug: content pushed off side

### ISSUE THREAD

**Issue by nikonikoniko** [DW-ReCo/kid-game-framework#95]
On certain screen sizes, the content is pushed off the side of the activity-hub.  This is because of a bulma container: 

![2021-11-05-155840_3840x2160_scrot](https://user-images.githubusercontent.com/1519292/140531622-72f390a2-3cad-460b-9476-c59871248f0d.png)

**Comment by nikonikoniko** [comment]
I would really _love_ for the activities to max-width themselves to the `66vw` that the whole hub takes

**Comment by nikonikoniko** [comment]
Reassign to me if you want me to take over, but i'll probably take the bulma out of the high-level panel stuff

**Comment by basilesimon** [comment]
I think it's because we're being a bit heavy-handed there, more than it is a Bulma issue:

```css
.hub-container {
  width: 50rem;
  max-width: calc(min(100vw, 100%));
  min-width: 50rem;
  margin: 0 auto;
}
```
